[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
fail_on_revert = false
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
